requestCPU: 1
requestMemory: 2G
limitCPU: 1
limitMemory: 2G
storageSize: 10Gi
checkClearbladeReadiness: true
regions:
version:
volumeHandle:
credentialsSource: "values"
gsmSecretName: iotcore-credentials
credentials:
  mailgun:
    API_KEY: ""
    DOMAIN: ""
    SENDER: ""
  masterCreds:
    email: ""
    password: ""
    systemKey: ""
