apiVersion: v2
name: clearblade-monitoring
description: ClearBlade IoT Enterprise monitoring
type: application
version: 2.14.7

dependencies:
  - name: cb-monitoring
    version: 2.14.7
    condition: cb-monitoring.enabled
    repository: file://charts/cb-monitoring
  - name: cb-haproxy
    version: 2.14.7
    condition: cb-haproxy.enabled
    repository: file://charts/cb-haproxy
