{{- if .Values.highAvailability }}
apiVersion: v1
kind: Service
metadata:
  name: cb-redis-sentinel-service
  namespace: {{ default "clearblade" $.Values.global.namespace }}
spec:
  clusterIP: None
  ports:
  - port: 5000
    targetPort: 5000
    name: sentinel
  selector:
    app: cb-redis-sentinel
---
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: cb-redis-service
  namespace: {{ default "clearblade" $.Values.global.namespace }}
spec:
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  {{- if .Values.global.monitoringEnabled }}
  - port: 9121
    protocol: TCP
    name: metrics
  {{- end }}
  selector:
    app: cb-redis