apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: {{ default "clearblade" .Values.global.namespace }}
  labels:    
{{ include "cb-redis.labels" . | indent 4 }}
data:
{{ (tpl (.Files.Glob "configs/redis.conf").AsConfig .) | indent 2 }}