apiVersion: v1
kind: Service
metadata:
  name: clearblade-service
  namespace: {{ default "clearblade" .Values.global.namespace }}
  labels:
    {{- if .Values.global.enterpriseSlot }}
    slot: {{ .Values.global.enterpriseSlot }}
    {{- else }}
    slot: blue
    {{- end }}
spec:
  {{- if .Values.reverseProxy.enabled }}
  type: LoadBalancer
  ports:
    {{- if .Values.reverseProxy.enableHttp }}
    - name: api
      port: {{ .Values.reverseProxy.httpPort }}
      targetPort: 9000
      protocol: TCP
    {{- end }}
    {{- if .Values.reverseProxy.enableHttps }}
    - name: api-https
      port: {{ .Values.reverseProxy.httpsPort }}
      targetPort: 9002
      protocol: TCP
    {{- end }}
    {{- if .Values.reverseProxy.enableMtls }}
    - name: mtls
      port: {{ .Values.reverseProxy.mtlsPort }}
      targetPort: 9001
      protocol: TCP
    {{- end }}
    {{- if .Values.reverseProxy.enableMqttInsecure }}
    - name: mqtt
      port: {{ .Values.reverseProxy.mqttInsecurePort }}
      targetPort: 1883
      protocol: TCP
    {{- end }}
    {{- if .Values.reverseProxy.enableMqtt }}
    - name: mqtt-tls
      port: {{ .Vaalues.reverseProxy.mqttPort }}
      targetPort: 1884
      protocol: TCP
    {{- end }}
    {{- if .Values.reverseProxy.enableMqttWsInsecure }}
    - name: mqtt-ws
      port: {{ .Values.reverseProxy.mqttWsInsecurePort }}
      targetPort: 8903
      protocol: TCP
    {{- end }}
    {{- if .Values.reverseProxy.enableMqttWs }}
    - name: mqtt-ws-tls
      targetPort: 8904
      port: {{ .Values.reverseProxy.mqttWsPort }}
      protocol: TCP
    {{- end }}
    {{- if .Values.reverseProxy.enableMqttAuthInsecure }}
    - name: mqtt-auth
      targetPort: 8905
      port: {{ .Values.reverseProxy.mqttAuthInsecurePort }}
      protocol: TCP
    {{- end }}
    {{- if .Values.reverseProxy.enableMqttAuth }}
    - name: mqtt-auth-tls
      targetPort: 8906
      port: {{ .Values.reverseProxy.mqttAuthPort }}
      protocol: TCP
    {{- end }}
    {{- if .Values.reverseProxy.enableMqttWsAuthInsecure }}
    - name: mqtt-ws-auth
      targetPort: 8907
      port: {{ .Values.reverseProxy.mqttWsAuthInsecurePort }}
      protocol: TCP
    {{- end }}
    {{- if .Values.reverseProxy.enableMqttWsAuth }}
    - name: mqtt-ws-auth-tls
      targetPort: 8908
      port: {{ .Values.reverseProxy.mqttWsAuthPort }}
      protocol: TCP
    {{- end }}
    {{- if .Values.reverseProxy.enableEdgeRpc }}
    - name: edge-rpc
      targetPort: 8951
      port: {{ .Values.reverseProxy.edgeRpcPort }}
      protocol: TCP
    {{- end }}
  {{- else }}
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
      protocol: TCP
    - name: mqtt-ws
      targetPort: 8903
      port: 8903
      protocol: TCP
    - name: mqtt-auth
      targetPort: 8905
      port: 8905
      protocol: TCP
    - name: mqtt-ws-auth
      targetPort: 8907
      port: 8907
      protocol: TCP
    - name: edge-rpc
      targetPort: 8950
      port: 8950
      protocol: TCP
    - name: api
      targetPort: 9000
      port: 9000
      protocol: TCP
    - name: mtls
      targetPort: 9001
      port: 9001
      protocol: TCP
  {{- end }}
  selector:
    app: clearblade
    {{- if .Values.global.enterpriseSlot }}
    slot: {{ .Values.global.enterpriseSlot }}
    {{- else }}
    slot: blue
    {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: clearblade-cluster-nodes-service
  namespace: {{ default "clearblade" .Values.global.namespace }}
  labels:
    app: clearblade
{{ include "clearblade.labels" . | indent 4 }}
spec:
  clusterIP: None
  ports:
    - name: clearblade-node
      targetPort: 8952
      port: 8952
      protocol: TCP
  selector:
    app: clearblade
{{- if eq (default .Values.global.gmpEnabled false) false }}
---
{{- if .Values.global.monitoringEnabled }}
{{- range $i, $e := until (.Values.blueReplicas | int)}}
apiVersion: v1
kind: Service
metadata:
  name: clearblade-monitoring-service-{{$i}}
  namespace: {{ default "clearblade" $.Values.global.namespace }}
  labels:
    run: clearblade
    slot: blue
spec:
  ports:
  - name: metrics
    port: 2112
    protocol: TCP
  selector:
    statefulset.kubernetes.io/pod-name: clearblade-{{$i}}
---
{{- end }}
{{- range $i, $e := until (.Values.greenReplicas | int)}}
apiVersion: v1
kind: Service
metadata:
  name: clearblade-monitoring-service-green-{{$i}}
  namespace: {{ default "clearblade" $.Values.global.namespace }}
  labels:
    run: clearblade
    slot: green
spec:
  ports:
  - name: metrics
    port: 2112
    protocol: TCP
  selector:
    statefulset.kubernetes.io/pod-name: clearblade-green-{{$i}}
---
{{- end}}
{{- end}}
{{- end}}

