{{- include "clearblade.statefulset" (dict 
  "name" "clearblade"
  "slot" "blue"
  "replicas" .Values.blueReplicas
  "partition" .Values.bluePartition
  "root" .
) }}
---
{{- include "clearblade.statefulset" (dict 
  "name" "clearblade-green"
  "slot" "green"
  "replicas" .Values.greenReplicas
  "partition" .Values.greenPartition
  "root" .
) }}