{{- if .Values.global.gcp }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clearblade-gsm-read
  namespace: {{ default "monitoring" .Values.global.namespace }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.global.gcpGSMServiceAccount }}@{{ .Values.global.gcpProject }}.iam.gserviceaccount.com
{{- end}}
{{- if and (eq .Values.global.cloud "aws") .Values.global.awsHelmRoleArn }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clearblade-asm-read
  namespace: {{ default "monitoring" .Values.global.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.global.awsHelmRoleArn }}
{{- end}}