apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: pubsub-emulator
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: grpc
      protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: pubsub-emulator
    release: {{ .Release.Name }}
