apiVersion: v1
kind: Secret
metadata:
  name: wg-postgres-temp-client
  # TODO: set to your namespace
  namespace: REPLACE_NAMESPACE
type: Opaque
stringData:
  wg0.conf: |
    [Interface]
    Address = 10.13.13.2
    PrivateKey = REPLACE_WITH_CLIENT_PRIVATE_KEY
    ListenPort = 51820
    DNS = off

    [Peer]
    PublicKey = REPLACE_WITH_SERVER_PUBLIC_KEY
    PresharedKey = REPLACE_WITH_PRESHARED_KEY
    Endpoint = REPLACE_NODE_EXTERNAL_IP:REPLACE_NODE_PORT
    AllowedIPs = REPLACE_PRIMARY_POD_IP/32
