apiVersion: v1
kind: Secret
metadata:
  name: wg-postgres-temp-client
  namespace: community
type: Opaque
stringData:
  wg0.conf: |
    [Interface]
    Address = 10.13.13.2
    PrivateKey = yBMrS0UhioJ0e1bw8ohDc1ok4nIZRyqPCTOfi0m0/V4=
    ListenPort = 51820
    DNS = off

    [Peer]
    PublicKey = 5e7rnA/Mx/U8I0r9o41bvw38OHxSDoghNkSGPrfg5FU=
    PresharedKey = Urz8fPgzLd4Si4/+qcETVvaZ+pV1TJ9g/OVR3vtZJrw=
    Endpoint = 136.112.6.206:31820
    AllowedIPs = 10.92.3.63/32
