{{- if .Values.alerts.slack.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: {{ default "monitoring" .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      securityContext: 
        runAsUser: 0
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64
      containers:
        - name: alertmanager
          image: prom/alertmanager:latest
          # resources:
          #   requests:
          #     cpu: {{ .Values.requestCPU }}
          #     memory: {{ .Values.requestMemory }}
          #   limits:
          #     cpu: {{ .Values.limitCPU }}
          #     memory: {{ .Values.limitMemory }}
          volumeMounts:
            - name: alertmanager-config-volume
              mountPath: /etc/alertmanager
      volumes:
        - name: alertmanager-config-volume
          secret:
            secretName: alertmanager
      {{- if .Values.global.nodePool }}
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .Values.global.nodePool }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-service
  namespace: {{ default "monitoring" .Values.global.namespace }}
spec:
  clusterIP: None
  ports:
  - port: 9093
    targetPort: 9093
    name: alertmanager
  selector:
    app: alertmanager
{{- end}}