{{- if or (ne $.Values.global.cloud "gdc") ($.Values.global.enablePersistentVolumes) }}
{{- range $i, $e := until (.Values.replicas | int)}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ default "clearblade" $.Values.global.namespace}}-postgres-{{$i}}
  namespace: {{ default "clearblade" $.Values.global.namespace }}
spec:
  storageClassName: {{ $.Values.global.storageClassName }}
  {{- if eq $.Values.global.cloud "aws" }}
  persistentVolumeReclaimPolicy: Retain
  {{- end }}
  capacity:
    storage: {{ $.Values.storageSize }}
  accessModes:
    - ReadWriteOnce
  csi:
  {{- if eq $.Values.global.cloud "gcp" }}
    driver: pd.csi.storage.gke.io
    {{- if $.Values.volumeHandle}}
    volumeHandle: "{{ $.Values.volumeHandle }}"
    {{- else }}
    volumeHandle: "projects/{{ $.Values.global.gcpProject }}/regions/{{ $.Values.global.gcpRegion }}/disks/{{ default "clearblade" $.Values.global.namespace }}-{{ $.Values.postgresDiskName }}-{{$i}}"
    {{- end }}
    fsType: ext4
  {{- else if eq $.Values.global.cloud "gdc"}}
    driver: "{{ $.Values.global.driver }}"
    volumeHandle: "{{ $.Values.global.postgresVolumeHandle }}"
    fsType: "{{ $.Values.global.fsType }}"
  {{- else if eq $.Values.global.cloud "aws" }}
  driver: ebs.csi.aws.com
  volumeHandle: {{ $.Values.volumeHandle }}
  {{- end }}
---
{{- end }}
{{- end }}